apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*'
build:
  local:
    push: false
  #googleCloudBuild:
   # projectID: tokyo-nomad-394418 
  artifacts:
    #- image: us.gcr.io/tokyo-nomad-394418/auth
    - image: binayakbehera999/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: binayakbehera999/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: binayakbehera999/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
